before_script:
  - apt-get update -y
  - apt-get install -y autoconf autopoint pkg-config tcl-dev liblua5.3-dev gettext libssl-dev libidn11-dev zlib1g-dev locales-all

build:
  script:
    - ./Makefile.git dist
    - ./configure --enable-debug=info --enable-ipv6 --with-rusnet --prefix=$(pwd)/.install
    - make install
