/* Automatically generated by po2tbl.sed from foxeye.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"joined this botnet channel.", 2},
  {"quit botnet: %s", 3},
  {"no reason.", 4},
  {"left this botnet channel.", 5},
  {"login timeout", 6},
  {"connection lost", 7},
  {"OOPS! No such user", 8},
  {"user has no password yet", 9},
  {"authentication failed", 10},
  {"Logged in: %s.", 11},
  {"Connected bots:\n", 12},
  {"Other people on the bot or on the botnet:\n", 13},
  {"Nothing appropriated to: %s", 14},
  {"Usage: ", 15},
  {"Listening socket on port %s terminated.", 16},
  {"DCC GET %s from %s terminated.", 17},
  {"cannot create socket", 18},
  {"access denied", 19},
  {"Listening socket died.", 20},
  {"((unknown))", 21},
  {"Connection from %s dropped: not allowed.", 22},
  {"Connection from %s lost while logging in.", 23},
  {"Get file \"%s\" from %s", 24},
  {"Resume file \"%s\"", 25},
  {"Overwrite existing file \"%s\"", 26},
  {"DCC GET aborted: couldn't open \"%s\".", 27},
  {"DCC GET aborted: couldn't create connection to %s:%hu.", 28},
  {"Got file \"%s\" from %s: %lu bytes instead of %lu.", 29},
  {"Got incomplete file \"%s\" from %s: %lu/%lu bytes.", 30},
  {"DCC send connection granted to %s on port %hu.", 31},
  {"DCC send connection to %s on port %hu closed.", 32},
  {"Sorry, my limit of DCC is exhausted. Try later, please.", 33},
  {"I'm sorry, no duplicate connections allowed.", 34},
  {"DCC CHAT: Duplicate connection attempt.", 35},
  {"DCC: Cannot create thread!", 36},
  {"Now: %s", 37},
  {"now away: %s", 38},
  {"returned to life.", 39},
  {"No such person at the botnet!", 40},
  {"Cannot boot the bot owner!", 41},
  {"You not permitted to boot a bot master!", 42},
  {"I don't know how to boot it!", 43},
  {"%s booted by %s@%s.", 44},
  {"messages", 45},
  {"commands", 46},
  {"connections/shares", 47},
  {"server messages", 48},
  {"wallops", 49},
  {"userfile changes", 50},
  {"debug", 51},
  {"other crap", 52},
  {"public", 53},
  {"joins/parts", 54},
  {"mode changes", 55},
  {"Your console logs", 56},
  {", and ", 57},
  {"on the channel", 58},
  {"No such user on DCC now", 59},
  {"%s has no password yet", 60},
  {"Users on this channel:", 61},
  {"Already listening on port %s!", 62},
  {"Cannot open listening port on %hu%s!", 63},
  {" for bots", 64},
  {"Listening on port %s%s.", 65},
  {"Cannot get hostname!", 66},
  {"Cannot resolve own IP!", 67},
  {"kill PID file", 68},
  {"The bot already running!\n", 69},
  {"init dispatcher", 70},
  {"Cannot run without a nick!", 71},
  {"Cannot write a PID file!", 72},
  {"DCC connection to %L lost.", 73},
  {"DCC chat to %L closed: %*.", 74},
  {"DCC get \"%*\" with %N established.", 75},
  {"Get file \"%*\" from %N completed.", 76},
  {"Input connection from %@:%P, ident %*.", 77},
  {"No help on this.", 78},
  {"Available topics for \"help%s%s\":", 79},
  {"%s (y/n)?[%c] ", 80},
  {"Current value of %s: %ld", 81},
  {"Current value of %s: %s%s", 82},
  {"Current value of %s: %s", 83},
  {"List of variables:", 84},
  {"Current format %s: %s", 85},
  {"List of formats:", 86},
  {"\
Universal network client %V.\n\
Operating system %s, hostname %@, started %*.", 87},
  {"case-sensitive ", 88},
  {"full match     ", 89},
  {"mask match     ", 90},
  {"first key only ", 91},
  {"first mask only", 92},
  {"  Bindtable %s:", 93},
  {"Success", 94},
  {"Fail", 95},
  {"Killed by %s%c %s", 96},
  {"Invalid configuration file!", 97},
  {"Cannot create configuration file.", 98},
  {"Out of memory!", 99},
  {"\
Usage:\tfoxeye [-n nick] [-cdmt] <file>\t\t- normal run\n\
\tfoxeye -cr [-n nick] [-dm] [-g <file>]\t- run with defaults\n\
\tfoxeye -[h|v]\t\t\t\t- print info and return\n\
\n\
options:\n\
  -c\t\tdon't detach console (chat simulation mode)\n\
  -d\t\tincrease a debug level by one\n\
  -g <file>\tgenerate a config file\n\
  -h\t\tthis help message\n\
  -m\t\tmake an empty user and channel files\n\
  -n <nick>\tset default nick\n\
  -r\t\treset parameters (don't use the config file statements)\n\
  -t\t\ttest the configuration and exit\n\
  -v\t\tversion information\n\
   <file>\tconfig file name\n", 100},
  {"\
Copiright (C) 1999-2002 Andriy Gritsenko.\n\
\n\
System: %s %s on %s.\n", 101},
  {"Incorrect options. Type 'foxeye -h' for more help.\n", 102},
  {"Added hostmask %s for name %s.", 103},
  {"Deleted hostmask %s from name %s.", 104},
  {"Added name %s with flag(s) %s.", 105},
  {"Added name %s.", 106},
  {"Added alias %s for %s.", 107},
  {"Deleted name %s.", 108},
  {"No user with login name %s found.", 109},
  {"owner", 110},
  {"master", 111},
  {"operator", 112},
  {"half op", 113},
  {"OOPS, you are not %s anymore...", 114},
  {"WOW, you are %s now...", 115},
  {"Global attributes for %s are now: %s.", 116},
  {"No such channel '%s'.", 117},
  {"You set no default channel yet.", 118},
  {"OOPS, you are not %s on %s anymore...", 119},
  {"WOW, you are %s on %s now...", 120},
  {"Channel attributes for %s on %s are now: %s.", 121},
  {"Cannot add user, one may be already exists.", 122},
  {"Password for %s erased.", 123},
  {"Cannot load userfile!", 124},
  {"Cannot save userfile!", 125},
};
int _msg_tbl_length = 125;
